### ISSUE TITLE
Filter PHPUnit (and its dependencies) from profile information

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-tideways-listener#1]

**Comment by sebastianbergmann** [comment]
@beberlei Do you think that this is something that should be done in the extension or in userland (here in this component, probably using `PHPUnit\Util\Blacklist`)?

**Comment by beberlei** [comment]
@sebastianbergmann there is no feature in the extension that allows filtering certain functions, so you need to filter in userland. Problem is the keys are "parent==>child" pairs, you should filter every call where a child is from PHPUnit

**Comment by sebastianbergmann** [comment]
Thank you, @beberlei.
